/**
* John Abraham
* Email: jpa18@pitt.edu
* CS 449: Project 1
* Rock. Paper, Scissors (30 points)
* Rules: scissors cuts paper, paper covers rock, rock breaks scissors
* Best-of-5 tournaemnt
* First to win three games wins the match
*/

#include <stdio.h>
#include <stdlib.h>
#include <string.h>

char *rand_choice();	//random computer choice generator function prototype

int main(void)
{
	srand(time(NULL)); // we need to seed the random number generator at the beginning of our program everytime we run it in order to get a truly random sequence of numbers
	char start[3]; // stores the user's answer 'yes' or 'no' if they want to play or not

	printf("Welcome to Rock, Paper, Scissors \n\n");
	// this do while loop is here to make sure that the user either enters 'yes' to play or 'no' to quit. otherwise, it keeps asking until they answer 'yes' or 'no'
	do
	{
		printf("Would you like to play ? ");
		scanf("%s", start);
	}while(strcmp(start, "yes") && strcmp(start, "no"));

	printf("\n");

	// this while loop keeps looping within the block until either the user or the computer wins the game.
	//Then the prgram asks the user to play again by choosing'yes' or quit by choosing 'no'
	while( !strcmp(start, "yes") )
	{
		int user_overall = 0; 	//this int keeps track of how many matches the player won
		int computer_overall = 0;	//this int keeps track of how many matches the computer won

		// this while loop keeps the tournament going until either the computer or the player reaches 5 won matches first and wins the tournament
		while(user_overall != 5 && computer_overall != 5)
		{

			int user_tally = 0;	//this int stores the player's score for each game
			int computer_tally = 0;	//this int stores the computer's score for each game

			//this while loop keeps the game going until either the computer or the player reaches 3 win first and wins the match
			while(user_tally != 3 && computer_tally != 3)
			{
				char user_choice[10];
				char *computer_choice = rand_choice(); // Here I set the computer_chioce equal to the random choice generated by my rand_choice function

				printf("What is your choice ? ");
				scanf("%s", user_choice);

				if(!strcmp(user_choice, "rock") && !strcmp(computer_choice, "scissors"))
				{
					user_tally++;
					printf("The computer chooses scissors. You win this game! ");
				}
				else if(!strcmp(user_choice, "rock") && !strcmp(computer_choice, "paper"))
				{
					computer_tally++;
					printf("The computer chooses paper. You lose this game! ");
				}			
				else if(!strcmp(user_choice, "paper") && !strcmp(computer_choice, "rock"))
				{
					user_tally++;
					printf("The computer chooses rock. You win this game! ");
				}
				else if(!strcmp(user_choice, "paper") && !strcmp(computer_choice, "scissors"))
				{
					computer_tally++;
					printf("The computer chooses scissors. You lose this game! ");
				}
				else if(!strcmp(user_choice, "scissors") && !strcmp(computer_choice, "paper"))
				{
					user_tally++;
					printf("The computer chooses paper. You win this game! ");
				}
				else if(!strcmp(user_choice, "scissors") && !strcmp(computer_choice, "rock"))
				{
					computer_tally++;
					printf("The computer chooses rock. You lose this game! ");
				}

				else if(!strcmp(user_choice, "rock") && !strcmp(computer_choice, "rock"))
				{
					printf("The computer also chooses rock. This game is a tie! \n");
				}

				else if(!strcmp(user_choice, "paper") && !strcmp(computer_choice, "paper"))
				{
					printf("The computer also chooses paper. This game is a tie! \n");
				}

				else if(!strcmp(user_choice, "scissors") && !strcmp(computer_choice, "scissors"))
				{
					printf("The computer also chooses scissors. This game is a tie! \n");
				}
				else
				{
					printf("Your choice is invalid. Please enter a valid choice. rock, paper, or scissors \n");
				}

				printf("The score is now you: %d computer: %d \n", user_tally, computer_tally);
			}

			if(user_tally > computer_tally)
			{
				user_overall++;
				printf("\nYOU WON THE MATCH! ");
			}

			if(user_tally < computer_tally)
			{
				computer_overall++;
				printf("\nYOU LOST THE MATCH! ");
			}

			printf("Player overall score is %d/5. Computer overall score is %d/5 \n", user_overall, computer_overall);

			// skip this part if tournament is over and proceed
			if(user_overall != 5 && computer_overall != 5)
			{
				// this do while loop again makes sure nothing happens until the user enters a valid answer 'yes' to play or 'no' to quit
				do
				{
					printf("Would you like to play again? ");
					scanf("%s", start);
					if(!strcmp(start, "no"))
						return;

				}while(strcmp(start, "yes") && strcmp(start, "no"));
			}
			printf("\n");
		}

		if(user_overall > computer_overall)
			printf("CONGRATULATIONS! YOU WON THE TOURNAMENT! ");
		if(user_overall < computer_overall)
			printf("THE COMPUTER WON THE TOURNAMENT! ");

		// this do while loop again makes sure nothing happens until the user enters a valid answer 'yes' to start a new tournament or 'no' to quit
		do
		{
			printf("Would you like to start a new tournament? ");
			scanf("%s", start);
			if(!strcmp(start, "no"))
				return;
		}while(strcmp(start, "yes") && strcmp(start, "no"));
		printf("\n");

	}
}

char *rand_choice() //function that generates a random computer choice
{
	int rand_int = rand()%(3 -1 +1)+1;		//gives a range of ints 1 to 3 according to the formula int value = rand()%(high - low +1)+low

	// If the random number generator generates a '1' then the function returns "rock" and sets it equal to the computer choice
	if(rand_int ==1)
	{
		return "rock";
	}

	// If the random number generator generates a '2' then the function returns "paper" and sets it equal to the computer choice
	if(rand_int == 2)
	{
		return "paper";
	}

	// If the random number generator generates a '3' then the function returns "scissors" and sets it equal to the computer choice
	if(rand_int == 3)
	{
		return "scissors";
	}
}
